### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by siyuan126** [archtk1010/sql-scratch-capstone-turn-in#2]
**Criteria 1: Report**
Score Level: 3 (Meets Expectations)
Comment(s): Your slides are very well designed. The table of contents and splash pages between sections are much appreciated and ease the flow of information. Every answer is expected to have three components: 1) SQL queries, 2) output tables as evidence, 3) text interpreting the query results. You did a great job to include all of them and display them in a very balanced way. However, the background color of SQL queries is a little too light, making it hard to see. Recommend to use a darker background. For first touch insights, second touch insights you order campaigns in a ascending order, I would recommend present the results in a descending order, since campaigns that drive more first touches and second touches are more important, and it's good to see the important ones first. 

**Criteria 2: Query Accuracy**
Score Level: 4 (Exceeds Expectations)
Comment(s): All queries accurately retrieve the data intended.

**Criteria 3: Query Formatting**
Score Level: 4 (Exceeds Expectations)
Comment(s): Queries adhere to the rules of the style guide. Good work using aliases to rename the columns and using indentation to organize your subqueries, both make your queries more readable!

**Criteria 4: Understanding underlying concepts and terminology**
Score Level: 4 (Exceeds Expectations)
Comment(s): Report demonstrates a good understanding of the dataset. It shows that you thought about all components of the data and how they link together. You understand the business problems, query the right table to get the results and explain it in a easy understood way. I specially like the recommendations you made. They show that you really put your shoes in the company's shoes and think from different perspectives. 

**Overall Score: 15/16**
Overall, GREAT job! You master the SQL queries, explain the results and make recommendations. This project shows that you have the ability to solve real world business problems using technique skills. I would recommend work on the presentation more, you are encouraged to use more creative visualization to present the results. For example, you can have a histogram chart to present first touch, last touch, purchase side by side.

**Comment by archtk1010** [comment]
Thanks for the review. Appreciate your feedback and will work on the presentational elements.
